# Generated by Django 5.0.3 on 2024-03-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Plan.user')),
                ('major', models.CharField(default='Undecided', max_length=100)),
                ('major2', models.CharField(default='NA', max_length=100)),
                ('minor1', models.CharField(default='NA', max_length=100)),
                ('minor2', models.CharField(default='NA', max_length=100)),
                ('grad_year', models.CharField(max_length=100)),
                ('entered', models.CharField(max_length=100)),
            ],
            bases=('Plan.user',),
        ),
    ]
