# Generated by Django 5.0.2 on 2024-04-18 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0009_plan_unique_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
