# Generated by Django 5.0.2 on 2024-04-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0016_remove_course_semester_remove_semester_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Plan.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='plan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Plan.plan'),
        ),
    ]
