# Generated by Django 4.2.13 on 2024-05-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0028_merge_20240508_0222'),
        ('Plan', '0028_merge_20240508_1344'),
    ]

    operations = [
    ]
