# Generated by Django 5.0.2 on 2024-03-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0004_rename_minor1_student_minor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='advisor',
            name='department',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='advisor',
            name='school',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='major2',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor2',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
