# Generated by Django 5.0.2 on 2024-03-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0005_remove_user_department_remove_user_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='major2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor',
            field=models.CharField(default='Studio Art', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor2',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
