# Generated by Django 5.0.2 on 2024-04-15 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0006_alter_student_major_alter_student_major2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField(unique=True)),
                ('courses', models.ManyToManyField(to='Plan.course')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Plan.student')),
                ('semester_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freshman_fall', to='Plan.semester')),
                ('semester_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freshman_spring', to='Plan.semester')),
                ('semester_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sophomore_fall', to='Plan.semester')),
                ('semester_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sophomore_spring', to='Plan.semester')),
                ('semester_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junior_fall', to='Plan.semester')),
                ('semester_6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junior_spring', to='Plan.semester')),
                ('semester_7', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_fall', to='Plan.semester')),
                ('semester_8', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_spring', to='Plan.semester')),
            ],
        ),
    ]
