# Generated by Django 5.0.2 on 2024-04-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0007_course_alter_student_major_alter_student_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
