# Generated by Django 5.0.2 on 2024-04-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0010_plan_plan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='semester_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshman_fall', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshman_spring', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sophomore_fall', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sophomore_spring', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior_fall', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior_spring', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_fall', to='Plan.semester'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='semester_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_spring', to='Plan.semester'),
        ),
    ]
