# Generated by Django 5.0.2 on 2024-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0012_remove_semester_courses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('user', 'plan_number')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course_1_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course_2_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course_3_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course_4_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course_5_code',
        ),
        migrations.AddField(
            model_name='plan',
            name='semesters',
            field=models.ManyToManyField(to='Plan.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='Plan.course'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_3',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_4',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_5',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_6',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_7',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semester_8',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='unique_semesters',
        ),
    ]
