# Generated by Django 5.0.2 on 2024-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0013_alter_plan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_num',
            field=models.CharField(choices=[('1', 'Freshman Fall'), ('2', 'Freshman Spring'), ('3', 'Sophomore Fall'), ('4', 'Sophomore Spring'), ('5', 'Junior Fall'), ('6', 'Junior Spring'), ('7', 'Senior Fall'), ('8', 'Senior Spring')], default='1', max_length=2),
        ),
    ]
