# Generated by Django 5.0.2 on 2024-04-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0018_alter_course_semester_alter_semester_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Plan.semester'),
        ),
    ]
