# Generated by Django 5.0.2 on 2024-04-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0020_remove_course_semester_remove_semester_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plan',
            name='s1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s7',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='s8',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_number',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
