# Generated by Django 5.0.2 on 2024-04-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0021_remove_semester_courses_alter_plan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Plan.student'),
        ),
    ]
