# Generated by Django 5.0.2 on 2024-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0025_plan_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='students',
            field=models.ManyToManyField(blank=True, to='Plan.student'),
        ),
    ]
