# Generated by Django 5.0.2 on 2024-05-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0026_advisor_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='students',
        ),
    ]
