# Generated by Django 5.0.2 on 2024-05-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0026_alter_plan_s1_alter_plan_s2_alter_plan_s3_and_more'),
        ('Plan', '0027_remove_advisor_students'),
    ]

    operations = [
    ]
