# Generated by Django 5.0.6 on 2024-05-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0030_alter_plan_s1_alter_plan_s2_alter_plan_s3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='s1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s3',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s4',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s5',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s6',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s7',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s8',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
